baseurl = "/"
languageCode = "fa-ir"
languageLang = "fa"
title = "6side jewelry"

# Enable relative URLs for better deployment compatibility
relativeURLs = false
canonifyURLs = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["rss", "taxonomy", "term"]

[params]
images = ["img/og-image.jpg"]